#
# Specific Views
# 

views:
  dummy:
    url: https://dummyjson.com/products?limit=100
    keypath: 
      - products
    format: json
    limit: 20
    # Uncomment 'multiply' field to get 100*10K=1M records for bulk test
    multiply: 10000
    



#
# Viewdir (can be many, path to directory, where one file is view)
#

viewdir:
  - sample

#
# Evalidate configuration
# Be careful when allow new node or attribute
#

nodes:
  - List
  - Call
  - Attribute
attrs:
  - startswith
  - endswith

  
  